# Generated by Django 3.1.6 on 2021-02-07 00:14

import blacklist.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[blacklist.validators.validate_CPF])),
            ],
            options={
                'verbose_name_plural': 'list entries',
            },
        ),
    ]
